### ISSUE TITLE
Week 6 - Week 7

### ISSUE THREAD

**Issue by phu0n9** [mnskgrayce/real-estate-mgt#3]
- [x] change folder name to match master, change folder structure to be separated by class @0xMYsteRy 
- [x] research data generation @phu0n9 
- [x] update class diagram and merge backend @mnskgrayce 

**Front-end Team:**: @qorcp  @longtransnt
- [x] redo mock layouts to reflect a single rental company, implement by ReactJS or NextJS

**Back-end Team**: @phu0n9 @mnskgrayce @0xMYsteRy 
- [x] display mock data on real pages, implement search/pagination support, research security

Should be updated on: 30/11

**Comment by 0xMYsteRy** [comment]
update project structure to match master branch
